### PR TITLE
Do not bind route of  non diego application

### PR DESCRIPTION
**Pull request by antechrestos**
Even if non diego application may be free minded, their routes do not support being bound (see #154)

@gberche-orange : do you confirm this behaviour? 

> _Diego, libre dans sa tête, s'endort peut-être_

### CODE REVIEW

**Comment by arnaudruffin** [comment]
We should discuss if we should handle diego/non-diego app at the same time. Isn't just the whole CF instance service-routing-compatible? 
I feel bad about having  a "route binding compatibility" field in the `ApplicationActivity` object and in the `updateDiagnosticInfo` method.

**Comment by antechrestos** [comment]
So do I but it is one or the other. So far if we want our code to work we must filter on these applications

**Comment by arnaudruffin** [comment]
What about something that testing for the 60021 error at the start of the application?

**Comment by antechrestos** [comment]
Really depending on the CF error syntax...

**Comment by arnaudruffin** [comment]
Lucky we don't depend on _your_ syntax \o/

**Comment by antechrestos** [comment]
:angry:

**Comment by antechrestos** [comment]
@arnaudruffin I did not update `db.changelog-master.yml` yet. If you can/ want to update it feel free to add a `Boolean` `ignoreRouteServiceError`

**Comment by arnaudruffin** [comment]
@antechrestos OK for the DB shema update, I will do it. I think we should also update the README in the same PR.

**Comment by arnaudruffin** [comment]
did you run the acceptance tests? I tried to run the first one but get the following error : 

```
pybot --pythonpath acceptance acceptance/1_service_broker_lifecycle.robot
[ ERROR ] Error in file '/Users/Arnaud/Dev/ElPaaso/autosleep/acceptance/Keywords.robot': Initializing test library 'Cloudfoundry' with arguments [ https://api.nd-cfapi.itn.ftgroup | True | user | mdp | brokers-sandboxes | autosleep-sample-space2 | static-test-arno | http://autosleep-arno.cf.ns.nd-paas.itn.ftgroup | autosleep-arno | yyy | xxx | my-autosleep-acc | {u'idle-duration': u'PT20S', u'exclude-from-auto-enrollment': u'.*', u'autosleep-despite-route-services-error': u'true'} ] failed: Only version 2 is supported for now. Found 0
```

I have already run `pip install --upgrade cloudfoundry-client`

**Comment by antechrestos** [comment]
No it is not an issue on the `service broker`side but rather on the api side. The api you're using is returning a `version` equal to 0 when requesting `/info` service. To get rid over it I made a [modification](https://github.com/antechrestos/cf-python-client/commit/2e4ea9599d1d7bee55ad10ce43ee3bfa245be228) on the [client](https://github.com/antechrestos/cf-python-client).I made a [new version](https://pypi.python.org/pypi?:action=display&name=cloudfoundry-client&version=0.0.8) of the client api.

**Comment by arnaudruffin** [comment]
@antechrestos This time I think we are good. Assigning it to you for the final merge.

**Comment by arnaudruffin** [comment]
(rebased from develop, after merge of PR #102 )
By the way, we forgot to mention in commit comments that these will fix issue #86

**Pull request merged**
