### PR TITLE
Adopt to latest cf-java-client and adapt requisite apis

### PR DESCRIPTION
**Pull request by pradyutsarma**

### CODE REVIEW

**Comment by pradyutsarma** [comment]
@gberche-orange I'm guessing I missed the mandated null checks with the latest java client release. Just to be sure, can you share the findbugs report from the travis build? I don't know how to access it within the build.

**Comment by gberche-orange** [comment]
@pradyutsarma Thanks for the PR. I'm out of office until Jan 8th. I don't believe travis stores the intermediate reports. You might have to reproduce locally instead.

**Comment by pradyutsarma** [comment]
No problem @gberche-orange. The build's green now. You can review and merge once you're back from vacation. This PR should fix https://github.com/cloudfoundry-community/autosleep/issues/285 and https://github.com/cloudfoundry-community/autosleep/issues/283

**Comment by gberche-orange** [comment]
thanks @pradyutsarma 

I ran the acceptance tests (after upgrading them), and completed the autowakeup with manual tests against a CF version 281. 

I'll push associated additional commits to the develop branch (acceptance tests + logs)

**Pull request merged**
