### PR TITLE
add service instance params in service binding returned credentials

### PR DESCRIPTION
**Pull request by arnaudruffin**

### CODE REVIEW

**Comment by antechrestos** [comment]
Something disturbs me: Suppose the following scenario
1. I create a service instance 
2. The created service instance is bound to some applications with the parameters. These parameters are copied to the service binding object
3. The service instance is updated
In this scenario your service binding object will have wrong values. Since these values are not really useful for the application itself, we _may_ do one of the following:
A. either create a service binding for the result only
B. update the binding on each ApplicationBinder iteration 
C. do not persist it
D. The D proposition
...

**Comment by arnaudruffin** [comment]
If I understand you're worried about the `credentials` parameter of the ApplicationBinding in our repository. 
But the issue you're raising is much bigger: these credentials are only send to the CF environment during **the creation of the binding**. CF copy these credentials in the env of the bound app, and won't ask it again. 

**So even if we were updating correctly these values (or won't persist it, they would never appear in CF** :scream:

=> _maybe we should simply reconsider this feature..._

**Comment by gberche-orange** [comment]
We agreed to have most of the autosleep service instance state being immutable https://github.com/Orange-OpenSource/autosleep/issues/81 (such as idle-duration), should remove need to have binding credentials being updated.

Besides, only the information relevant to the application should be returned in binding credentials: duration (e.g. filter out exclude-regexp)

**Comment by arnaudruffin** [comment]
Ok, I will update the PR to reflect this decision

**Comment by antechrestos** [comment]
Please add immutability of inactivity (just remove from `AutosleepServiceInstance.updateFromParameters`)

**Pull request merged**
